### ISSUE TITLE
Где инструкция по переходу?

### ISSUE THREAD

**Issue by rik43** [yoomoney/yookassa-sdk-php#15]
Композер выдает предупреждения о переходе. 
в старом модуле yoomoney/yandex-checkout-sdk-php история закончилась на версии 1.6.9. 
здесь уже появилась 2.0. 
Были какие то изменения? 
или я просто поменяю на yoomoney/yookassa-sdk-php и ничего не сломается? не хотелось бы с платежами рисковать.

**Comment by ostulov** [comment]
Добрый день!

Были удалены некоторые классы и методы, которые ранее были помечены на deprecated.
При переходе кроме замены в composer.json на
"yoomoney/yookassa-sdk-php": "2.0"
необходимо везде заменить YandexCheckout\ на YooKassa\
