### ISSUE TITLE
переход с одной либы на другую 

### ISSUE THREAD

**Issue by olegatro** [yoomoney/yookassa-sdk-php#2]
Доброй ночи. 

Композер тут пишет что yandex пакет не укатуален уже, и надо качать этот. 

Собственно вопросик простой - кроме названия классов в коде надо еще что менять? 

Очень мягко выражусь - не доволен я тем фактом что надо менять пакет для платежки, это ведь бабки. 

Знаю знаю, все обещают мягко всех подготовить к переезду - ну ну.

Ладно давайте по существу, есть дока по миграции ? или все легко и просто и надо лишь сменить названия классов

**Comment by 350d** [comment]
Я вчера переехал, имена классов поменял (у меня в одном только месте их пара и все) и сегодня вижу аномально высокий уровень жалоб и проблем с платежами, каждый второй - ошибка платежа. Ничего не менялось кроме либы и если часть платежей работает, значит новая работает, но что с платежами я не знаю.

**Comment by olegatro** [comment]
Жду ответа, дорогой ребрендинг сбера , а шол бы ты ...

**Comment by ostulov** [comment]
Добрый день!

Сами классы не меняли названия. Сменилось только пространство имен.
Дополнительно были удалены deprecated классы, свойства и методы.

Для получения оперативной помощи Вы всегда можете обратиться в службу технической поддержки ЮKassa:
8 800 250-66-99
yamoney_shop@yoomoney.ru

**Comment by olegatro** [comment]
Ага, спасибо.

**Comment by pdapnz** [comment]
@ostulov Коллеги, а в issue или на сайте в документации не судьба написать что конкретно поменялось?
Все эти изменения как снег на голову. Сегодня просто перестал работать платежный виджет. Как так-то?
