### ISSUE TITLE
Uncaught Error: Class 'YooKassa\Client' not found

### ISSUE THREAD

**Issue by gbyts** [yoomoney/yookassa-sdk-php#3]
В одной папке лежат 2 версии
libold - https://github.com/yoomoney/yandex-checkout-sdk-php
libnew - https://github.com/yoomoney/yookassa-sdk-php
 
если вызывать
require_once('libnew/autoload.php');
use YooKassa\Client;
$client = new Client();
То появляется ошибка - Fatal error: Uncaught Error: Class 'YooKassa\Client' not found in (строка $client = new Client();)
 
если вызывать старый sdk:
require_once('libold/autoload.php');
use YandexCheckout\Client;
$client = new Client();
 
То все работает как прежде. Протестировано на php 5.3 и на php 7.1 - одинаково выходит ошибка.

**Comment by ostulov** [comment]
Добрый день!

Благодарю за обращение!
Передам информацию команде разработки, предварительно завтра выйдет обновление. которое решит эту проблему.

**Comment by gbyts** [comment]
Спасибо. В поддержке уже помогли, нужно в файле autoload.php заменить 

` if (strncmp('YooKassa', $className, 14) === 0) {
        $path   = YOOKASSA_SDK_ROOT_PATH;
        $length = 14;`
на
`if (strncmp('YooKassa', $className, 8) === 0) {
        $path   = YOOKASSA_SDK_ROOT_PATH;
        $length = 8;`

**Comment by ostulov** [comment]
Выпустили обновление библиотеки. в версии v2.0.2 проблема исправлена.
