### ISSUE TITLE
Обновления пакеты 

### ISSUE THREAD

**Issue by shokhaa** [yoomoney/yookassa-sdk-php#35]
Доброе времени суток! 
Много фреймворки уже перешли на новый пакеты PSR логи!
Если устанавливать этот lib то тогда composer даёт ошибку:

  Problem 1
    - yoomoney/yookassa-sdk-php[2.1.0, ..., 2.1.6] require psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
потому что у меня уже более новый версии psr/log

**Comment by ostulov** [comment]
Добрый день!

Благодарю за замечание, поправим!

**Comment by shokhaa** [comment]
Могу поправить и кидать pull request! 
или просто можно изменить зависимость 
с "psr/log": "^1.0.1" на "psr/log": "^1.0.1 || ^2.0 || ^3.0"
