### ISSUE TITLE
Метод me() не позволяет передать параметр 'on_behalf_of'

### ISSUE THREAD

**Issue by localusercamp** [yoomoney/yookassa-sdk-php#39]
Класс: `YooKassa\Client`
Метод: `me()`
Решение ЮКасса для платформ предполагает возможность извлечения данных по продавцам платформы. Для этого существует query-параметр `on_behalf_of` для `me()` запроса. В SDK же данный параметр через метод `me()` передать нельзя, из-за того, что `me()` не принимает параметров в принципе (хотя в кишках он вызывает `$this->execute`, в который кладет `null` для `$queryParams`). Было бы неплохо дать возможность передавать `$queryParams` в метод `me()`.

**Comment by ostulov** [comment]
Добрый день!

Благодарю за замечание, поправим!
