### ISSUE TITLE
Как передать merchant_customer_id при создании платежа?

### ISSUE THREAD

**Issue by Gesha87** [yoomoney/yookassa-sdk-php#41]
При создании платежа через метод `createPayment`, я передаю в массив `merchant_customer_id`, но SDK игнорирует это поле, так как в `CreatePaymentRequest` нет соответствующего метода.

Так же не принимаются `transfers` и `deal`. Все эти параметры были добавлены в API последними, видать до SDK обновление ещё не дошло.

**Comment by ostulov** [comment]
Добавили поддержку оставшихся полей
