### ISSUE TITLE
Баг при создании чека отмены платежа

### ISSUE THREAD

**Issue by janmare** [yoomoney/yookassa-sdk-php#55]
Добрый день.
При создании чека отмены холдированного платежа (https://yookassa.ru/developers/solutions-for-platforms/split-payments/receipts#receipt-for-canceled-payment) происходит ошибка:
`{
	"type": "error",
	"id": "***",
	"code": "invalid_request",
	"description": "Refund not found or forbidden",
	"parameter": "refund_id"
}`

В методе serializeObjectId принудительно устанавливается поле refund_id вместо payment_id.

**Comment by ostulov** [comment]
Добрый день!

Приложите, пожалуйста, конкретный код, с помощью которого Вы формируете запрос.
Также желательно уточнить id операции, для которой Вы хотите сделать этот чек.

**Comment by janmare** [comment]
А можно по почте с вами как-то связаться?

**Comment by ostulov** [comment]
Да, Вы можете отправить информацию на почту cms@yoomoney.ru.
Я лично получу Ваше письмо.

**Comment by ostulov** [comment]
Исправлено в последнем обновлении v2.2.7
