### ISSUE TITLE
Поддержка СБП (Система быстрых платежей)

### ISSUE THREAD

**Issue by rik43** [yoomoney/yookassa-sdk-php#59]
падает ошибка 
Invalid payment method data type "sbp"

в строчке 
https://github.com/yoomoney/yookassa-sdk-php/blob/master/lib/Model/PaymentMethod/PaymentMethodFactory.php#L75

т.к. в массиве выше https://github.com/yoomoney/yookassa-sdk-php/blob/master/lib/Model/PaymentMethod/PaymentMethodFactory.php#L38

нет sbp.

планируется добавить?

**Comment by ostulov** [comment]
Добрый день!

Да, в ближайшее время сделаем обновление SDK с полноценной поддержкой нового способа оплаты.

**Comment by rik43** [comment]
а с порядком сроков не сориентируете? неделя? две? месяц?

**Comment by ostulov** [comment]
Уже добавили в сегодняшнем обновлении [v2.3.0](https://github.com/yoomoney/yookassa-sdk-php/releases/tag/2.3.0)
