### ISSUE TITLE
Yookassa/Client class not found

### ISSUE THREAD

**Issue by zavitkov** [yoomoney/yookassa-sdk-php#6]
Добрый день.

Перешел с Вашего старого SDK на этот после перехода на yookassa. 

Почему-то получаю вот такую ошибку: 
"message":"Class 'Yookassa\\Client' not found"

При этом в IDE (PHPStorm) класс нормально отображается, и я в него без проблем могу перейти. 

Используем Laravel 5.8.

Аналогичный решенный ISSUE я прочитал (https://github.com/yoomoney/yookassa-sdk-php/issues/3), но у меня установлена версия Вашего SDK 2.0.3, в которой данной проблемы уже быть не должно.

Возможно, у Вас будут идеи, почему такое происходит?

Спасибо!

**Comment by ostulov** [comment]
Добрый день!

В коде для импорта нужного класса проверьте регистр. Буква K должна быть заглавной.

**Comment by zavitkov** [comment]
Да, проблема была именно в этом. 
Прошу прощения за невнимательность!
Спасибо!
