### ISSUE TITLE
Значения `income_amount` и `test` не устанавливаются в PaymentsResponse

### ISSUE THREAD

**Issue by 01-10** [yoomoney/yookassa-sdk-php#7]
При получении списка платежей через `getPayments()` у объектов Payment в списке не устанавливается информация об `income_amount` и `test`, поэтому соотвествующие геттеры у таких объектов возвращают null.

Из API эти данные поступают, но не устанавливаются в `YooKassa\Request\Payments\PaymentsResponse@__construct`.

**Comment by ostulov** [comment]
Добрый день!

Благодарю за замечание, поправим.

**Comment by ostulov** [comment]
Исправление выложено.
