### ISSUE TITLE
Метод addRecieptItem не поддерживает передачу параметров Supplier и agentType

### ISSUE THREAD

**Issue by musicalbee** [yoomoney/yookassa-sdk-php#8]
В классе AbstractPaymentRequestBuilder есть метод addRecieptItem (https://github.com/yoomoney/yookassa-sdk-php/blob/427c05f0cf31ee0ac3afcaedcc9c9b65ea4f352b/lib/Common/AbstractPaymentRequestBuilder.php#L243) в который на данный момент невозможно передать информацию о поставщике товаров.

Я использую ваше расширение cms-prestashop и в модели Кассы (KassaModel.php) мне не хватает возможности передать информацию о поставщике товаров.

Подскажите, пожалуйста, когда можно ожидать обновление SDK и вашего модуля для PrestaShop?

П.с. Возможно, есть другой способ передеть эту информацию в чек, буду рад вашим предложениям :)

**Comment by ostulov** [comment]
Добрый день!

Параметры supplier и agentType используются только при отправке чека отдельным запросом (https://yookassa.ru/developers/54fz/basics#receipt-after-payment), а не вместе с запросом на платеж. 

В SDK это метод createReceipt:
https://github.com/yoomoney/yookassa-sdk-php/blob/3eebc00ef25e7170ced6d3c0da98e8581c3cbc5e/lib/Client.php#L701
